force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Used in the JOINTHEDIGITALHUB service</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DM_Asset.cls
/**
 * @File Name          : DM_Asset.cls
 * @Description        : 
 * @Author             : taniaoliveirafartaria@gmail.com
 * Ver       Date            Author      		    Modification
 * 1.0    27/05/2020   taniaoliveirafartaria@gmail.com     Initial Version
**/
public class DM_Asset {
    
    public static List<Asset> getAssetsByIds(Set<Id> assetIds){

        List<Asset> assetRecords = new List<Asset>([
            SELECT Id, 
            Description, 
            Country__c,
            Product2.ExternalId__c
            FROM Asset 
            WHERE Id IN :assetIds 
            AND Product2.ExternalId__c != null ]);
    
        return assetRecords;
    }




}